from pydantic import BaseModel, Field
from typing import Any


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=3,
        description="Natural language question about the orders dataset",
        examples=[
            "What is the total revenue from customer C001 in the last 30 days?",
            "Show me the latest 5 orders",
            "What is the average order value this month?",
        ],
    )


class AskResponse(BaseModel):
    answer: str = Field(
        ...,
        description="Natural-language answer generated by the service"
    )
    sql_used: str = Field(
        ...,
        description="SQLite query generated and executed by the service"
    )
    rows: list[dict[str, Any]] = Field(
        ...,
        description="Raw rows returned by the executed SQL query"
    )